trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - backend/**

parameters:
  - name: salt
    default: 'aks'
  - name: useWorkspace
    default: true
    type: boolean

variables:
  - template: variables.yml
  - name: saltVar
    ${{ if eq(parameters.useWorkspace, true) }}:
      value: ${{ parameters.salt }}
    ${{ else }}:
      value: ''

pool:
  vmImage: "ubuntu-latest"

jobs:
- job: Terraform
  displayName: Infrastructure
  steps:
    - template: terraform.yml
      parameters:
        terraformVersion: $(terraformVersion)
        terraformPath: $(terraformPath)
        servicePrinciple: $(servicePrinciple)
        containerName: $(terraformContainerName)
        storageAccountName: $(terraformStorageAccountName)
        workspace: ${{ variables.saltVar }}
        useWorkspace: ${{ parameters.useWorkspace }}
        resourceGroupName: $(terraformResourceGroupName)
        env:
          TF_VAR_branch: ${{ variables.saltVar }}